- main
- exceptions and tracebacks


# Main
Why need a **main method** in py file ?

coz of how Python's import system works.

If a python code is imported, any code in it gets executed.

Ex: **name_lib.py**
```py
def name_length(name):
    return len(name)

def upper_case_name(name):
    return name.upper()

name = "Mahi"
length = name_length(name)
upper_case = upper_case_name(name)

print(f"The length is {length} and the uppercase version is: {upper_case}")
```
```py
python hello.py # will log the print statement
The length is 4 and the uppercase version is: MAHI
```
If we try to re-use name_lib.py in another file, and run that

**another_file.py**
```py
import name_lib

my_name = "Vicky"

my_length = name_lib.name_length(my_name)
my_lower_case = name_lib.lower_case_name(my_name)

print(f"In this code, my length is {my_length} and my name is: {my_name}")
```
```py
python another_file.py
The length is 4 and the uppercase version is: MAHI  # Output 1
In this code, my length is 5 and my name is: Vicky  # Output 2
```

So Output 1 is unwanted here. To prevent this we need to add some condition.

that condition is , `__name__ == __main__`

`__name__` is a special variable that’s *set by Python* that tells it where it was called from, so changing it will effect execution.

__ is called double under score or dunder in python

```py
print(f"The value of __name__ is: {__name__}")

# this prints 

The value of __name__ is: name_lib
```
==> Usually, __name__ value will be __main__ for any *.py file, but When we “run” our library by importing it, we’ll see that it’s `__name__` is set to the name of the file that it’s in, minus the .py extension. In this case, `__name__ is set to name_lib`.

so put the code in main conditional
Ex: **name_lib.py**
```py
def name_length(name):
    return len(name)

def upper_case_name(name):
    return name.upper()

if __name__ = "__main__":
    name = "Mahi"
    length = name_length(name)
    upper_case = upper_case_name(name)

    print(f"The length is {length} and the uppercase version is: {upper_case}")

 # so this print runs, only when it is called.   

 print(__name__) # this prints __main__. So this values gets changed when file gets imported.
```

# Exceptions and tracebacks

```py
# this will throw an exception!
int("a")

print("End of the program.")
```

If we’re running our Python code from a file, **an uncaught** exception will quit the program.

In order to prevent our program from exiting, we’ll need to catch the Exception with a try except block. 

The anatomy of a try except block:
```
try:
    <code to try>
except ExceptionClass:
    <code to run if an exception happens>
```

```py
try:
    int("a")
except ValueError:
    print("Oops, couldn't convert that value into an int!")

print("Reached end of the program.")
```

## Accessing the Exception

Using `as` to access The Exception

assign a label to the exception, and the exception will be assigned to the variable you specified, so you can look at it’s message

`except <ExceptionClass> as <variable_name>`

```py
try:
    int("a")
except ValueError as error:
    print(f"Something went wrong. Message: {error}")

print("Reached end of the program.")
```

```py
# Output

Something went wrong. Message: invalid literal for int() with base 10: 'a'
Reached end of the program.
```

## Traceback

:information_source:
**Remember, to understand tracebacks, read them from bottom to top.**

```py
Traceback (most recent call last):
  File "/Users/nina/projects/2019-fem-python/python/content/02-introduction-to-python/175-running-code/code/exceptions.py", line 2, in <module>
    int("a")
ValueError: invalid literal for int() with base 10: 'a'
If we start reading from the bottom up, we’ll notice a lot of useful information.
```

- First, we’ll see the exception that was thrown, along with its class ValueError.
- Next, we’ll see the code that caused the Exception.
- One line up from that, we’ll see the path and the file the exception originated in, as well as the line number to look on.